#!/bin/bash

export CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
export CONFIGTX_ORDERER_BATCHTIMEOUT=2s
export KAFKA_DEFAULT_REPLICATION_FACTOR=3
export CORE_LOGGING_GOSSIP=WARNING
export ORDERER_GENERAL_TLS_ENABLED=false
export ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
export ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
export ORDERER_TLS_CLIENTAUTHREQUIRED=false
export CORE_PEER_TLS_ENABLED=false
export CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
export CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
export CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
export ORDERER_ABSOLUTEMAXBYTES="10 MB"
export ORDERER_PREFERREDMAXBYTES="512 KB"
export KAFKA_MESSAGE_MAX_BYTES="1000012 B"
export KAFKA_REPLICA_FETCH_MAX_BYTES="1048576 B"
export KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES="10485760 B"
export ARCH=$(arch)
bash